apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
  - protocol: "TCP"
    port: 5005
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: ecrurl:latest
        imagePullPolicy: Never
        env:
        - name: ATC_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: ATC_USER
        - name: ATC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: ATC_PASS
        ports:
        - containerPort: 5000
