apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
spec:
  selector:
    app: hello-python
  ports:
  - protocol: "TCP"
    port: 5005
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
spec:
  selector:
    matchLabels:
      app: hello-python
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: hello-python
        image: hello-python:latest
        imagePullPolicy: Never
        env:
        - name: ATC_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: ATC_USER
        - name: ATC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: ATC_PASS
        ports:
        - containerPort: 5000
